
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.dev
    #ports:
    #  - "9003:9003" # Xdebug port
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini