# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.output_dir: '%kernel.project_dir%/var/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    # Auto-wire and auto-configure scrapers
    App\Factory\ScraperFactory:
        arguments:
            $scrapers:
                ebay: '@App\Scraper\EbayCategoryScraper'

    App\Scraper\EbayCategoryScraper:
        arguments:
            $baseUrl: '%env(EBAY_SEARCH_BASE_URL)%'

    App\Service\ProductService:
        arguments:
            $csvDirectory: '%app.output_dir%/products'

    App\MessageHandler\ProductWriteMessageHandler:
        arguments:
            $productService: '@App\Service\ProductService'
        tags: ['messenger.message_handler']
